# action.yml
name: 'Terraform Cloud Workspace setup'
description: 'Setup a Terraform Cloud/Enterprise workspace'
inputs:
  hostname:
    description: 'Terraform Cloud hostname'
    required: true
    default: "app.terraform.io"
  organization:
    description: 'Terraform Cloud Organization name'
    required: true
  organization_email:
    description: 'Terraform Cloud Organization email'
    required: true
  workspaces:
    description: 'Terraform Cloud Workspaces definitions and variables'
    required: true
  token:
    description: 'Terraform Cloud API token'
    required: true
outputs:
  organization_id:
    description: 'The created or updated Terraform Organization ID'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.organization }}
    - ${{ inputs.organization_email }}
    - ${{ inputs.workspaces }}
    - ${{ inputs.token }}
    - ${{ inputs.hostname }}
branding:
  icon: 'check-square'
  color: 'blue'
